### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by fitwist** [BPouncey/ReactJS-ecommerce-template#4]
After running 'npm i' in the repo directory I try to start the development via 'npm start' and get a TypeError:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:317:13)
    at /Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:317:13)
    at /Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/helenkapatsa/Repositories/ReactJS-ecommerce-template/node_modules/express/lib/router/layer.js:95:5)

Environment: macOS 10.15.6
npm@6.14.8

**Comment by fitwist** [comment]
Either for 'yarn start'

**Comment by stepankudelia** [comment]
The same problem here

**Comment by stepankudelia** [comment]
1. Replace in your package.json "react-scripts": "^3.x.x" with "react-scripts": "^3.4.1" (or the latest available version)
2. (optional for some) Delete your node_modules folder
3. Run npm install or yarn install

**Comment by bruceallday** [comment]
Thanks for this I have updated all deps.
